### ISSUE TITLE
Interface/BI for Report

### ISSUE THREAD

**Issue by DariaKhot** [gregorysycle/cis4400fall2024#10]
The final interface will be a web-based application where the Persona can visualize the results.
People should be able also to connect to your data using Tableau/PowerBI and do their own
analysis. Elaborate on how we used the BI tool

**Comment by tlax-daniel** [comment]
You can access the report at the following link:
[Looker Studio Report](https://lookerstudio.google.com/reporting/a45c370d-5933-4161-8707-0b5132dee9e3)

The following graphs, along with the page number they're on, have been completed:

Treemap: Dollar Volume by Industry (Page 1)
Bar Chart: Dollar Volume by Sector (Page 2)
Bar Chart: Dollar Volume by Security (Page 3)
Time Series Chart: Average Price Over Time by Trading Symbol (Page 4)

If there are any recommendations for improvement, please let me know
